In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

In [2]:
os.chdir('c:\\Users\\quinn\\Sberbank') 

In [3]:
train=pd.read_csv('trainVariables2.csv')

In [4]:
train.fillna(train.median(), inplace = True)

In [5]:
q=train['full_sq'].quantile(.99)
data_1=train[train['full_sq']<q]

In [6]:
r=data_1['floor'].quantile(.99)
data_2=data_1[data_1['floor']<r]

In [7]:
s=data_2['green_zone_part'].quantile(.99)
data_3=data_2[data_2['green_zone_part']<s]

In [8]:
t=data_3['kremlin_km'].quantile(.99)
data_4=data_3[data_3['kremlin_km']<t]

In [9]:
u=data_4['price_doc'].quantile(.99)
data_5=data_4[data_4['price_doc']<u]

In [10]:
new_data=data_5.reset_index(drop=True)

In [11]:
x=new_data.iloc[:, :-1].values
y=new_data.iloc[:, -1].values

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=101)

In [14]:
y_test = y_test.reshape(len(y_test),1)

In [15]:
#try this along with the one below: y_test = y_test.reshape(len(y_test),1)

In [16]:
y_train = y_train.reshape(len(y_train),1)

In [17]:
#try this: y_train = y_train.reshape(len(y_train),1)

In [18]:
sc_x_train=StandardScaler()
sc_y_train=StandardScaler()
x_train=sc_x_train.fit_transform(x_train)
y_train=sc_y_train.fit_transform(y_train)

C:\Users\quinn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\quinn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [19]:
sc_x_test=StandardScaler()
sc_y_test=StandardScaler()
x_test=sc_x_test.fit_transform(x_test)
y_test=sc_y_test.fit_transform(y_test)

C:\Users\quinn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\quinn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [20]:
from sklearn.svm import SVR
regressor = SVR(kernel ='rbf')
regressor.fit(x_train, y_train)

C:\Users\quinn\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), 1))

[[-0.13  0.07]
 [ 0.27  0.26]
 [-0.19 -0.25]
 ...
 [-1.01 -0.98]
 [-0.67 -1.06]
 [-0.44 -0.24]]


In [30]:
sc_y_test.inverse_transform(regressor.predict(sc_x_test.transform(x_test)))

array([7596179.4 , 7760040.81, 6802670.65, ..., 7506808.03, 8115391.32,
       8068941.76])

In [23]:
from sklearn import metrics

In [24]:
print("RMSE", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

RMSE 0.7014078364421201


In [27]:
metrics.r2_score(y_test, y_pred)

0.508027046977584

In [26]:
sc_y_test.inverse_transform(regressor.predict(sc_x_test.transform(x_test)))

array([7596179.4 , 7760040.81, 6802670.65, ..., 7506808.03, 8115391.32,
       8068941.76])